In [3]:
import pandas as pd

In [16]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
s.dtype
s.values
s.index

RangeIndex(start=0, stop=6, step=1)

In [8]:
print(s.name)

None

In [ ]:
s.name="calories"
print(s.name)

numbers

In [ ]:
s[0:3]
s[2:4]

0    10
1    20
2    30
Name: numbers, dtype: object

In [12]:
#iloc -> location based indexing
s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: object

In [ ]:
index=['apple','banana','mango','grapes','orange']

In [ ]:
s.index=index
s

apple     10
banana    20
mango     30
grapes    40
orange    50
dtype: int64

In [ ]:
#loc --> label based indexing
#in label based indexing we can use the index name to access the values, here both start and stop values are included
s.loc['banana']

np.int64(20)

In [23]:
fruit_protein = {'apple': 5, 'banana': 10, 'mango': 15, 'grapes': 20, 'orange': 25}

s2=pd.Series(fruit_protein, name='protein')
s2

apple      5
banana    10
mango     15
grapes    20
orange    25
Name: protein, dtype: int64

In [ ]:
# conditional selection
s2>5 #masked series 
s2[s2>5] #passing masked series to the original series to get the values

banana    10
mango     15
grapes    20
orange    25
Name: protein, dtype: int64

In [30]:
#logical operators

(s2>5) & (s2<20)
s2[(s2>5) & (s2<20)]

s2[(s2>5) | (s2<20)]

apple      5
banana    10
mango     15
grapes    20
orange    25
Name: protein, dtype: int64

In [33]:
#modifying series values    
s2['strawberry'] = 30
s2

s2['mango'] = 18
s2

apple          5
banana        10
mango         18
grapes        20
orange        25
strawberry    30
Name: protein, dtype: int64

In [35]:
#Dataframe practice
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [25, 30, 35, 0, 45], 'Department': ['HR', 'Finance', 'IT', 'Marketing', 'Sales'], 
        'Salary': [50000, 60000, 70000, 0, 90000]}

data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
 'Age': [25, 30, 35, 0, 45],
 'Department': ['HR', 'Finance', 'IT', 'Marketing', 'Sales'],
 'Salary': [50000, 60000, 70000, 0, 90000]}

In [4]:
df=pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30    Finance   60000
2  Charlie   35         IT   70000
3    David   40  Marketing   80000
4      Eva   45      Sales   90000

In [ ]:
#loc and iloc
df.iloc[1:3]

      Name  Age Department  Salary
1      Bob   30    Finance   60000
2  Charlie   35         IT   70000

In [6]:
df.loc[1:3, ['Name', 'Salary']]

      Name  Salary
1      Bob   60000
2  Charlie   70000
3    David   80000

In [ ]:
df.iloc[1:3, :2] # rows, columns and the range for this are seperated by comma, 
#here we are selecting rows 1 and 2 and columns 0 and 1

      Name  Age
1      Bob   30
2  Charlie   35

In [9]:
df[["Age","Department"]] #this will give an error as we are trying to access multiple columns using single square brackets, we need to use double square brackets

   Age Department
0   25         HR
1   30    Finance
2   35         IT
3   40  Marketing
4   45      Sales

In [ ]:
# dropping a column
df.drop('Age', axis=1) #without inplace=True, this will return a new dataframe with the column dropped, 
#but the original dataframe will remain unchanged

      Name Department  Salary
0    Alice         HR   50000
1      Bob    Finance   60000
2  Charlie         IT   70000
3    David  Marketing   80000
4      Eva      Sales   90000

In [ ]:
df.drop('Age', axis=1, inplace=True) #with inplace=True, the original dataframe will be modified and the column will be dropped permanently

In [11]:
df.shape #gives the number of rows and columns in the dataframe

(5, 4)

In [12]:
df.info() #gives the summary of the dataframe, including the number of non-null values, data types, and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [13]:
df.describe() #gives the summary statistics of the numerical columns in the dataframe, including count, mean, standard deviation, minimum, maximum, and quartiles

             Age        Salary
count   5.000000      5.000000
mean   35.000000  70000.000000
std     7.905694  15811.388301
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    35.000000  70000.000000
75%    40.000000  80000.000000
max    45.000000  90000.000000

In [15]:
#Broadcasting in pandas

df["Salary"] = df["Salary"] * 1.1 #increasing salary by 10%
df["Salary"]

0     60500.0
1     72600.0
2     84700.0
3     96800.0
4    108900.0
Name: Salary, dtype: float64

In [17]:
df.rename(columns={'Department': 'Dept'}, inplace=True) #renaming a column, with inplace=True, the original dataframe will be modified and the column will be renamed permanently
df

      Name  Age       Dept    Salary
0    Alice   25         HR   60500.0
1      Bob   30    Finance   72600.0
2  Charlie   35         IT   84700.0
3    David   40  Marketing   96800.0
4      Eva   45      Sales  108900.0

In [18]:
df["Salary"].unique() #gives the unique values in the Salary column

array([ 60500.,  72600.,  84700.,  96800., 108900.])

In [19]:
df["Dept"].unique() #gives the unique values in the Dept column

array(['HR', 'Finance', 'IT', 'Marketing', 'Sales'], dtype=object)

In [ ]:
df["Dept"].value_counts() #gives the count of unique values in the dept column, this will give an error as we have renamed the column to Dept, so we need to use Dept instead of dept

Dept
HR           1
Finance      1
IT           1
Marketing    1
Sales        1
Name: count, dtype: int64

In [23]:
df["Promoted Salary"]= df["Salary"]*10.0
df

      Name  Age       Dept    Salary  Promoted Salary
0    Alice   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [25]:
# data Cleaning

df.isnull() #gives a boolean dataframe indicating the presence of null values

df.isnull().sum() #gives the count of null values in each column

Name               0
Age                0
Dept               0
Salary             0
Promoted Salary    0
dtype: int64

In [26]:
#dropping or removing null values from a dataframe

df.dropna() #this will return a new dataframe with the null values dropped, but the original dataframe will remain unchanged

df.dropna(inplace=True) #with inplace=True, the original dataframe will be modified and the null values will be dropped permanently

df

      Name  Age       Dept    Salary  Promoted Salary
0    Alice   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [29]:
df.dropna(how='any') #this will drop the rows where any of the values are null, this is the default behavior of dropna( )

df.dropna(how='all') #this will drop the rows where all of the values are null, this will not drop any rows as there are no rows where all values are null
df

      Name  Age       Dept    Salary  Promoted Salary
0    Alice   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [34]:
# Dealing with missing values

#option 1 - fill with most repeated values using fillna()
#option 2 - getting rid of them using dropna()

df.fillna(0)

df.fillna(method='ffill') #this will fill the null values with the previous non-null value, this is called forward fill

df["Age"].fillna(df["Age"].mean())

df["Salary"].fillna(df["Salary"].median())

C:\Users\deepthi.b\AppData\Local\Temp\ipykernel_21484\4152427889.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill') #this will fill the null values with the previous non-null value, this is called forward fill

0     60500.0
1     72600.0
2     84700.0
3     96800.0
4    108900.0
Name: Salary, dtype: float64

In [37]:
#fillna has 2 methods
# 1. forward fill
# 2. backward fill

df["Age"].fillna(method='ffill') #this will fill the null values with the previous non-null value, this is called forward fill
df["Dept"].fillna(method='bfill') #this will fill the null values with the next non-null value, this is called backward fill
df

C:\Users\deepthi.b\AppData\Local\Temp\ipykernel_21484\1488723563.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='ffill') #this will fill the null values with the previous non-null value, this is called forward fill
C:\Users\deepthi.b\AppData\Local\Temp\ipykernel_21484\1488723563.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Dept"].fillna(method='bfill') #this will fill the null values with the next non-null value, this is called backward fill

      Name  Age       Dept    Salary  Promoted Salary
0    Alice   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [44]:
#renaming values

df["Name"].replace({'Rose','Bob'})
df

df['Name']= df['Name'].replace({'Rose':'Bob'}) #this will replace the value 'Alice' with 'Rose' in the Name column, and the original dataframe will be modified permanently
df

C:\Users\deepthi.b\AppData\Local\Temp\ipykernel_21484\3232231347.py:3: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df["Name"].replace({'Rose','Bob'})

      Name  Age       Dept    Salary  Promoted Salary
0      Bob   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [ ]:
#dealing with duplicates

df_dup=df[df.duplicated()]
df

      Name  Age       Dept    Salary  Promoted Salary
0      Bob   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [48]:
df_dup=df[df.duplicated(keep='last')] #works from bottom to top

df=df.drop_duplicates()
df

      Name  Age       Dept    Salary  Promoted Salary
0      Bob   25         HR   60500.0         605000.0
1      Bob   30    Finance   72600.0         726000.0
2  Charlie   35         IT   84700.0         847000.0
3    David   40  Marketing   96800.0         968000.0
4      Eva   45      Sales  108900.0        1089000.0

In [53]:
# invalid values
#Lambda 

df["Promoted Salary"] =  df["Promoted Salary"].apply(lambda x : x/10 if x > 7000 else x)
df

      Name  Age       Dept    Salary  Promoted Salary
0      Bob   25         HR   60500.0           6050.0
1      Bob   30    Finance   72600.0            726.0
2  Charlie   35         IT   84700.0            847.0
3    David   40  Marketing   96800.0            968.0
4      Eva   45      Sales  108900.0           1089.0

In [ ]:
name="alice_fernandes"
df[["first_name","second_name"]]=df["name"].str.split("_")

In [54]:
# apply and lambda 
def mul_age(x):
    return x*2

df["Age"]=df["Age"].apply(mul_age)
df

      Name  Age       Dept    Salary  Promoted Salary
0      Bob   50         HR   60500.0           6050.0
1      Bob   60    Finance   72600.0            726.0
2  Charlie   70         IT   84700.0            847.0
3    David   80  Marketing   96800.0            968.0
4      Eva   90      Sales  108900.0           1089.0

In [58]:
df["Age"]=df["Age"].apply(lambda x: x/2)
df

      Name   Age       Dept    Salary  Promoted Salary
0      Bob  12.5         HR   60500.0           6050.0
1      Bob  15.0    Finance   72600.0            726.0
2  Charlie  17.5         IT   84700.0            847.0
3    David  20.0  Marketing   96800.0            968.0
4      Eva  22.5      Sales  108900.0           1089.0

In [63]:
#joins in pandas

# left, right, outer, inner, merge

dept_info= {
    "Dept":["HR","IT","Product","Finance"],
    "Location": ["New York", "San", "India", "Japan"],
    "Manager": ["Laura", "Steve", "Kevin", "Radhya"]

}

df2=pd.DataFrame(dept_info)
df2

      Dept  Location Manager
0       HR  New York   Laura
1       IT       San   Steve
2  Product     India   Kevin
3  Finance     Japan  Radhya

In [ ]:
#concat
pd.concat([df, df2])

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Bob,12.5,HR,60500.0,6050.0,NaN,NaN,NaN
1,Bob,15.0,Finance,72600.0,726.0,NaN,NaN,NaN
2,Charlie,17.5,IT,84700.0,847.0,NaN,NaN,NaN
3,David,20.0,Marketing,96800.0,968.0,NaN,NaN,NaN
4,Eva,22.5,Sales,108900.0,1089.0,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,New York,Laura
1,NaN,NaN,NaN,NaN,NaN,IT,San,Steve
2,NaN,NaN,NaN,NaN,NaN,Product,India,Kevin
3,NaN,NaN,NaN,NaN,NaN,Finance,Japan,Radhya

In [61]:
pd.concat([df, df2], axis=1)

,Name,Age,Dept,Salary,Promoted Salary,Department,Location,Manager
0,Bob,12.5,HR,60500.0,6050.0,HR,New York,Laura
1,Bob,15.0,Finance,72600.0,726.0,IT,San,Steve
2,Charlie,17.5,IT,84700.0,847.0,Product,India,Kevin
3,David,20.0,Marketing,96800.0,968.0,Finance,Japan,Radhya
4,Eva,22.5,Sales,108900.0,1089.0,NaN,NaN,NaN

In [64]:
pd.merge(df,df2, on= 'Dept')

      Name   Age     Dept   Salary  Promoted Salary  Location Manager
0      Bob  12.5       HR  60500.0           6050.0  New York   Laura
1      Bob  15.0  Finance  72600.0            726.0     Japan  Radhya
2  Charlie  17.5       IT  84700.0            847.0       San   Steve

In [66]:
data=pd.read_csv("c:/Users/deepthi.b/Downloads/Schedule_Request_76_AdHoc_18062026.csv")

In [67]:
data.head()

,TEST_TYPE,PRIORITY,OCCURENCE,NUMBER_OF_JOBS,NUMBER_OF_TESTS,FREQUENCY,RUNS_ON,ORIGINATING_NUMBER,ORIGINATING_NETWORK,ROUTE,...,START_TIME,END_TIME,RECORD_ON,MAXIMUM_TEST_DURATION,RESERVED1,RESERVED2,RESERVED3,START_HOUR,END_HOUR,Force_Connect
0,SITE Simbox Test,1,AdHoc,1,4,D,NaN,TELCWOA1,ICPBWO,ICPB 20099,...,18-06-2026,18-06-2026,D,NaN,shoot_AdHoc_18JUN,NaN,NaN,00:00:00,23:59:00,No
1,SITE Simbox Test,1,AdHoc,1,4,D,NaN,BELCWOA3,ICPCWO,ICPC 1507194,...,18-06-2026,18-06-2026,D,NaN,shoot_AdHoc_18JUN,NaN,NaN,00:00:00,23:59:00,No
2,SITE Simbox Test,1,AdHoc,1,4,D,NaN,FLEVWOA0,FreecalleeVoIPWO,No Route,...,18-06-2026,18-06-2026,D,NaN,shoot_AdHoc_18JUN,NaN,NaN,00:00:00,23:59:00,No
3,SITE Simbox Test,1,AdHoc,1,4,D,NaN,TELCWOA1,ICPBWO,ICPB 20024,...,18-06-2026,18-06-2026,D,NaN,shoot_AdHoc_18JUN,NaN,NaN,00:00:00,23:59:00,No
4,SITE Simbox Test,1,AdHoc,1,4,D,NaN,TELCWOA1,ICPBWO,ICPB 20090,...,18-06-2026,18-06-2026,D,NaN,shoot_AdHoc_18JUN,NaN,NaN,00:00:00,23:59:00,No

In [68]:
data.shape

(204, 26)

In [69]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   TEST_TYPE                    204 non-null    object
 1   PRIORITY                     204 non-null    int64
 2   OCCURENCE                    204 non-null    object
 3   NUMBER_OF_JOBS               204 non-null    int64
 4   NUMBER_OF_TESTS              204 non-null    int64
 5   FREQUENCY                    204 non-null    object
 6   RUNS_ON                      0 non-null      float64
 7   ORIGINATING_NUMBER           204 non-null    object
 8   ORIGINATING_NETWORK          204 non-null    object
 9   ROUTE                        204 non-null    object
 10  TERMINATING_NUMBER           204 non-null    object
 11  TERMINATING_NETWORK          0 non-null      float64
 12  TERMINATING_EXTERNAL_NUMBER  0 non-null      float64
 13  FORWARDED_NUMBER             0 non-null      float64
 14  CLI_VISIBILITY               204 non-null    object
 15  CALL_DURATION                204 non-null    int64
 16  START_TIME                   204 non-null    object
 17  END_TIME                     204 non-null    object
 18  RECORD_ON                    204 non-null    object
 19  MAXIMUM_TEST_DURATION        0 non-null      float64
 20  RESERVED1                    204 non-null    object
 21  RESERVED2                    0 non-null      float64
 22  RESERVED3                    0 non-null      float64
 23  START_HOUR                   204 non-null    object
 24  END_HOUR                     204 non-null    object
 25  Force_Connect                204 non-null    object
dtypes: float64(7), int64(4), object(15)
memory usage: 41.6+ KB

In [71]:
# date is converted to object above, convert

data['START_TIME']=pd.to_datetime(data['START_TIME'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   TEST_TYPE                    204 non-null    object
 1   PRIORITY                     204 non-null    int64
 2   OCCURENCE                    204 non-null    object
 3   NUMBER_OF_JOBS               204 non-null    int64
 4   NUMBER_OF_TESTS              204 non-null    int64
 5   FREQUENCY                    204 non-null    object
 6   RUNS_ON                      0 non-null      float64
 7   ORIGINATING_NUMBER           204 non-null    object
 8   ORIGINATING_NETWORK          204 non-null    object
 9   ROUTE                        204 non-null    object
 10  TERMINATING_NUMBER           204 non-null    object
 11  TERMINATING_NETWORK          0 non-null      float64
 12  TERMINATING_EXTERNAL_NUMBER  0 non-null      float64
 13  FORWARDED_NUMBER             0 non-null      float64
 14  CLI_VISIBILITY               204 non-null    object
 15  CALL_DURATION                204 non-null    int64
 16  START_TIME                   204 non-null    datetime64[ns]
 17  END_TIME                     204 non-null    object
 18  RECORD_ON                    204 non-null    object
 19  MAXIMUM_TEST_DURATION        0 non-null      float64
 20  RESERVED1                    204 non-null    object
 21  RESERVED2                    0 non-null      float64
 22  RESERVED3                    0 non-null      float64
 23  START_HOUR                   204 non-null    object
 24  END_HOUR                     204 non-null    object
 25  Force_Connect                204 non-null    object
dtypes: datetime64[ns](1), float64(7), int64(4), object(14)
memory usage: 41.6+ KB